# Sanity check: 100 training videos, should overfit to near-zero loss within ~10 epochs.
# If it doesn't, there is a bug in the data pipeline or model.
dataset:
  max_video_len: 32
  max_len: 64
  meta_processor: SignCLIPVideoCSVMetaProcessor
  video_processor: RWTHFSVideoProcessor
  text_processor: TextProcessor
  bert_name: bert-base-cased
  splits_dir: /home/psobecki/ASL_Citizen/splits_tiny
  train_path: placeholder
  val_path: placeholder
  test_path: placeholder
  vfeat_dir: /home/psobecki/ASL_Citizen/i3d_features
  vfeat_custom: 1
  aligner: DSAligner
  sp_universal_tagging: true
  augment_temporal: false
fairseq:
  common:
    fp16: true
    tensorboard_logdir: run
    log_interval: 10
  dataset:
    num_workers: 2
    batch_size: 100
  optimization:
    lr:
    - 1.0e-10
    clip_norm: 2.0
    optimizer: adam
    adam_betas: (0.9, 0.98)
    lr_scheduler: polynomial_decay
    total_num_update: 1000000
    warmup_updates: 50
    weight_decay: 0.0
    ddp_backend: no_c10d
    max_epoch: 500
  checkpoint:
    no_epoch_checkpoints: true
    save_dir: runs/retri_asl/asl_citizen_cnn_sanity
task_type: sweep_small
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: null
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 12
  vfeat_dim: 1024
loss:
  loss_cls: MMContraLoss
eval:
  save_path: runs/retri_asl/asl_citizen_cnn_sanity
