dataset:
  max_video_len: 32
  max_len: 64
  split: test
  train_for_test: false
  meta_processor: SignCLIPVideoCSVMetaProcessor
  video_processor: RWTHFSVideoProcessor
  text_processor: TextProcessor
  bert_name: bert-base-cased
  splits_dir: /home/psobecki/wlasl100/splits
  vfeat_dir: /scratch-shared/psobecki/wlasl100/logos_features
  vfeat_custom: 1
  dataset_name: wlasl100_test
  aligner: DSAligner
  sp_universal_tagging: true
  test_separately: false
task_type: local_predict
fairseq:
  dataset:
    batch_size: 512
    num_workers: 4
  common_eval:
    path: runs/retri_asl/wlasl100_cnn_scratch_logos_nowd/checkpoint_best.pt
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: null
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 12
  vfeat_dim: 768
eval:
  save_path: runs/retri_asl/wlasl100_cnn_scratch_logos_nowd/eval
metric: RWTHFSMetric
predictor: RetrievalPredictor
