#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=asl_inv_trial
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --time=1:00:00
#SBATCH --output=jobs/output/slurm_%x_%A.txt

module purge
module load 2025

cd $HOME/Fork_SignCLIP/examples/MMPT
source .venv/bin/activate
export PYTHONPATH=$HOME/Fork_SignCLIP:$PYTHONPATH
export PATH="$HOME/Fork_SignCLIP/examples/MMPT/.venv/bin:$PATH"

python make_asl_citizen_pair_manifest.py \
    --aug_video_list /home/psobecki/ASL_Citizen/aug_selection/aug_video_list.txt \
    --logos_dir      /home/psobecki/ASL_Citizen/logos_features \
    --output         /home/psobecki/ASL_Citizen/asl_citizen_pair_manifest.json

srun python locallaunch.py \
    projects/retri/signclip_asl/asl_citizen_cnn_appearance_invariant.yaml \
    --jobtype local_single \
    fairseq.optimization.max_epoch=2
