#!/bin/bash

#SBATCH --partition=rome
#SBATCH --job-name=asl_poses
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=8:00:00
#SBATCH --output=jobs/output/slurm_asl_poses_%A.txt

module purge
module load 2025

cd $HOME/Fork_SignCLIP/examples/MMPT
source .venv/bin/activate
export PYTHONPATH=$HOME/Fork_SignCLIP:$PYTHONPATH
export PATH="$HOME/Fork_SignCLIP/examples/MMPT/.venv/bin:$PATH"

srun python extract_asl_citizen_poses.py \
    --video_dir  /scratch-shared/psobecki/ASL_Citizen/videos \
    --splits_dir $HOME/ASL_Citizen/splits \
    --output_dir $HOME/ASL_Citizen/mediapipe_features \
    --model_path $HOME/Fork_SignCLIP/examples/MMPT/holistic_landmarker.task \
    --workers    14
