#!/bin/bash
#SBATCH --partition=genoa
#SBATCH --job-name=form_dose_raw
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:25:00
#SBATCH --output=jobs/output/slurm_%x_%A.txt
module purge; module load 2025
cd $HOME/Fork_SignCLIP/examples/MMPT
source .venv/bin/activate
export PYTHONPATH=$HOME/Fork_SignCLIP:$PYTHONPATH
python form_dose.py --styles --space raw=/scratch-shared/psobecki/ASL_Citizen/logos_features_native
