#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=ngt_base
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --time=24:00:00
#SBATCH --output=jobs/output/slurm_%x_%A.txt

module purge
module load 2025

cd $HOME/Fork_SignCLIP/examples/MMPT
source .venv/bin/activate
export PYTHONPATH=$HOME/Fork_SignCLIP:$PYTHONPATH
export PATH="$HOME/Fork_SignCLIP/examples/MMPT/.venv/bin:$PATH"

srun python locallaunch.py projects/retri/signclip_ngt/ngt_baseline.yaml --jobtype local_single

python eval_ngt_retrieval.py \
    --config      projects/retri/signclip_ngt/ngt_baseline.yaml \
    --checkpoint  /scratch-shared/psobecki/runs/retri_ngt/ngt_baseline/checkpoint_last.pt \
    --manifest    /home/psobecki/ngt_pair_manifest.json \
    --bushuis_dir /scratch-shared/psobecki/Bushuis/logos_features
