#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=signclip_l2_probe_pose
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=1:00:00
#SBATCH --output=jobs/output/slurm_signclip_l2_probe_pose_%A.txt

module purge
module load 2025

cd $HOME/Fork_SignCLIP/examples/MMPT
source .venv/bin/activate
export PYTHONPATH=$HOME/Fork_SignCLIP:$PYTHONPATH
export PATH="$HOME/Fork_SignCLIP/examples/MMPT/.venv/bin:$PATH"

CACHE=/scratch-shared/psobecki/signclip_embed_cache

python asl_citizen_signclip_l2_probe.py \
    --config projects/retri/signclip_asl/test_asl_citizen_finetune_snellius.yaml \
    --model_name signclip_pose --cache_dir $CACHE
