#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=sc_augft_on_aug
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --time=03:30:00
#SBATCH --output=jobs/output/slurm_%x_%A.txt
module purge
module load 2025
cd $HOME/Fork_SignCLIP/examples/MMPT
source .venv/bin/activate
export PYTHONPATH=$HOME/Fork_SignCLIP:$PYTHONPATH
export PATH="$HOME/Fork_SignCLIP/examples/MMPT/.venv/bin:$PATH"
srun python locallaunch.py projects/retri/signclip_asl/signclip_augft_on_aug.yaml --jobtype local_single
python mmpt_cli/predict.py projects/retri/signclip_asl/test_signclip_augft_on_aug.yaml --quiet
echo DONE_sc_augft_on_aug
