#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=i3d_extract
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=08:00:00
#SBATCH --output=slurm_i3d_extract_%A.out

module purge
module load 2022
module load CUDA/12.6.0

cd $HOME/Fork_SignCLIP/examples/MMPT
source .venv/bin/activate
export PYTHONPATH=$HOME/Fork_SignCLIP:$PYTHONPATH

srun python extract_asl_citizen_i3d_features.py \
    --video_dir  /home/psobecki/ASL_Citizen/videos \
    --output_dir /home/psobecki/ASL_Citizen/i3d_features \
    --i3d_weights /home/psobecki/bsl5k.pth.tar \
    --batch_size 32
